### PR TITLE
Remove values like -999

### PR DESCRIPTION
**Pull request by dolugen**
For PM 2.5, I guess negative values would be invalid.

_tmp_openaq-viz

### CODE REVIEW

**Comment by jflasher** [comment]
I'm down with removing the negative values. I think it'd be better if we did something like `measurements?value_from=0` so that the filtering would happen on the API side. Also, since we're going to be dumping measurements, maybe we want to remove the line connecting everything since it'd no longer be accurate?

**Comment by dolugen** [comment]
> `measurements?value_from=0`

Oh that would be much simpler. Thanks for the input.

> remove the line connecting everything since it'd no longer be accurate?

What do you mean?

**Comment by jflasher** [comment]
@RocketD0g do you want to comment on the connection of the data points?

**Comment by RocketD0g** [comment]
I think the picture explains things better, but basically, if expected data is missing for a given time interval, what do you guys think about _not_ connecting the points around the gap so as to reflect that expected data is missing (e.g. method 2 below). This could be used for data that is already missing or is removed if < 0. While, a missing data point also reflects that data was not captured for that time interval, that can be hard to discern on a graph, especially if a large time frame is shown relative to the temporal resolution of the data itself - so the eye tends to just follow the line. Thoughts?

img_2063

**Comment by dolugen** [comment]
@RocketD0g I see. I didn't realise that was a problem.

There could be two other methods.

One is based on the method 1. Instead of a solid line, use a dashed line for the missing point.

(Example from here: [link](https://books.google.mn/books?id=LT1RXREvkGIC&pg=PA418&lpg=PA418&dq=graph+portraying+missing+data+points&source=bl&ots=A0vZcMNg1O&sig=uqPRNVbNG9ePPJRQFIHzLjL7Kxw&hl=en&sa=X&redir_esc=y#v=onepage&q=graph%20portraying%20missing%20data%20points&f=true))
screenshot from 2016-02-28 15 17 48

The other is more explicit, a method I saw here: [link](http://www.csueastbay.edu/FOCUS/wf761doc/ibi_html/javaassist/intl/EN/help/topic253.htm). The missing point is replaced with 0 and linked to others with dashed lines.

wf_cr_dottedline

**Comment by RocketD0g** [comment]
@dolugen - Oh, I think whatever we do regarding this ends up being more just stylistic preferences - no real absolute wrong or right about it. From a viewer's point of view, my personal preference (in order of preference) would be to go with a) Method # 2 in my previous post (green line),  b) your black and white example above with the dashed line going to the next available point, or c) keep what we have now on http://labs.openaq.org/aq-viz/ - a solid line skipping over the missing data point.   I personally don't like the replacement with '0' in the second figure above (purple line) because it arbitrarily breaks up the visual 'flow' of the actual data based on a non-real value and also may confuse some people at a glance.  @jflasher did say my (a) Method #2 in the previous post would be difficult to make, in which case I assume (b) is also difficult and may mean we just stick with (c) what we're doing now. All other thoughts welcome!

**Pull request merged**
